spring.application.name=hospital-grupo6

# Base de datos MySQL (Laragon por defecto)
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_grupo6?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Thymeleaf
spring.thymeleaf.cache=false

# Puerto
server.port=8080
